### ISSUE TITLE
MRP121 Capacitive Touch

### ISSUE THREAD

**Issue by malumuntu** [rottaca/LEDTableEngine#39]
HI ,

I'm trying to use an Adafruit MRP121 Capacitive Touch sensor via the i2c, and I'm having trouble getting the software to recognise it, would you be able to assist, or advise?

**Comment by rottaca** [comment]
I'm sorry to disappoint you. A sensor like this is not supported by the software.  You can implement your own input handler, similar to the i2c game controllers. Have a look at:
LEDTableEngine/include/LEDTableEngine/inputHandlers/gameControllerInput.hpp
and the corresponding cpp file:
LEDTableEngine/src/inputHandlers/gameControllerInput.cpp
