### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by brockr1993** [rottaca/LEDTableEngine#41]
I can't get this to work. I am getting this error when I run the setup.sh

pi@raspberrypi:~/LEDTableEngine $ ./scripts/setup.sh
-- lib2c-dev not found! I2C controller support disabeled.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/LEDTableEngine/build
[ 51%] Built target LEDTableEngine
[ 94%] Built target LEDTableApps
[ 97%] Building CXX object CMakeFiles/LEDTableMain.dir/main.cpp.o
/home/pi/LEDTableEngine/main.cpp:94:18: error: #elif with no expression
#elif

HELP!!

**Comment by Peatopper** [comment]
Hi, sorry it’s so long ago I really can’t remember the issue or solution. I did however get in touch with the person on Thingiverse that created the LED table and he helped get it running.

Sorry I couldn’t be more help good luck

Nick

**Comment by rottaca** [comment]
Hi,
Please take a look at my comment on issue #40.
